export const services = [
  {
    id: 's1',
    title: 'E-Commerce Photo Editing',
    slug: 'ecommerce-photo-editing',
    shortDescription: 'Comprehensive optimization for high-volume online retail catalogs.',
    description: '<p>Standardize your entire catalog with perfect lighting, alignment, and formatting. We ensure every product shot meets the high standards of global marketplaces like Amazon and eBay. Our complete workflow includes precise background removal to eliminate distractions, surgical clipping path isolation for crisp edges, and accurate color correction so your products always look true to life.</p>',
    priceStarting: 0.35,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Consistency across batches', 'Web-ready sizing', 'Color vibrancy boost', 'Marketplace compliance'],
    pricingData: [
      { type: 'Basic', price: '$0.35/image', desc: 'Standard packshots, simple products' },
      { type: 'Standard', price: '$0.75/image', desc: 'Reflective surfaces, small details' },
      { type: 'Complex', price: '$1.50/image', desc: 'Jewelry, bicycles, intricate items' },
      { type: 'Super Complex', price: '$3.00+/image', desc: 'Automotive, large multi-part assemblies' }
    ],
    targetAudience: [
      'Amazon FBA Sellers',
      'Shopify Store Owners',
      'eBay Power Sellers',
      'Retail Enterprise Catalogs',
      'Boutique Apparel Brands',
      'Commercial Photographers'
    ],
    customFaqs: [
      { q: "How fast can you process 1,000+ e-commerce images?", a: "We can process up to 3,000 images within 24 hours using our dedicated studio teams." },
      { q: "Do you offer free tests for new brands?", a: "Yes, upload up to 10 product images and we will edit them for free within 24 hours." },
      { q: "Do your edits meet Amazon & eBay standards?", a: "Absolutely. We guarantee 100% compliance with all major marketplace image requirements (pure white backgrounds, correct margins)." },
      { q: "Can I get volume discounts?", a: "Yes, we offer custom reduced pricing for daily or weekly high-volume batches." },
      { q: "What is your revision policy?", a: "We offer unlimited revisions until the images perfectly match your approved brand guidelines." }
    ],
    h2Title: 'What is E-Commerce Photo Editing?',
    schemaDescription: 'Professional e-commerce photo editing services for Amazon, Shopify, and eBay sellers. High-volume batch processing from $0.35/image. 24-hour turnaround.',
    beforeImage: '/ECommerce.jpg',
    afterImage: '/ECommerce-Done.jpg',
    order: 1,
    status: 'PUBLISHED'
  },
  {
    id: 's2',
    title: 'Background Removal',
    slug: 'background-removal-service',
    shortDescription: 'Flawless isolation of subjects with clean, professional transparency.',
    description: '<p>Pure subjects on pure backgrounds. Our experts use advanced techniques to remove distracting environments while preserving natural edges, fine details, and shadows.</p>',
    priceStarting: 0.29,
    priceUnit: 'image',
    turnaround: '12 hours',
    features: ['Transparent (.png) delivery', 'Pure white background option', 'Natural edge softening', 'Fast bulk turnaround'],
    beforeImage: '/bg_removal_compare_before_1774788191480.png',
    afterImage: '/bg_removal_compare_after_1774788208396.png',
    heroImage: '/bg_removal_studio_hero_1774788173759.png',
    workflowImage: '/bg_removal_workflow_edit_1774788226809.png',
    order: 2,
    status: 'PUBLISHED'
  },
  {
    id: 's3',
    title: 'Clipping Path Service',
    slug: 'clipping-path-service',
    heroLabel: 'Professional Service',
    shortDescription: 'Professional clipping path service for product photography, e-commerce and advertising. Hand-drawn pen tool paths in Adobe Photoshop for pixel-perfect edges. From $0.25/image. 24-hour delivery worldwide.',
    schemaDescription: 'Professional clipping path service starting from $0.25/image. Hand-drawn pen tool paths for pixel-perfect product isolation. 24-hour delivery. Trusted by 500+ global brands. Free trial available — no credit card required.',
    description: '<p>Clipping path is a photo editing technique that uses the Pen Tool in Adobe Photoshop to draw a precise vector path around a subject. This path is used to isolate the subject from its background, creating a clean, sharp edge perfect for product photography, e-commerce listings and advertising materials. Add our background removal, image masking, or e-commerce photo editing for a complete studio pipeline.</p>',
    priceStarting: 0.25,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Hand-drawn pen tool paths', 'Anti-aliased edges', 'Multiple nested paths', 'Non-destructive editing'],
    pricingData: [
      { type: 'Basic', price: '$0.25/image', desc: 'Simple shapes, straight distinct edges' },
      { type: 'Medium', price: '$0.49/image', desc: 'Small curves, multiple anchor points' },
      { type: 'Complex', price: '$1.00/image', desc: 'Vehicles, furniture, moderate details' },
      { type: 'Super Complex', price: '$3.00+/image', desc: 'Bicycles, chainlink, intricate cutouts' }
    ],
    targetAudience: [
      'E-Commerce Sellers (Amazon, eBay, Shopify)',
      'Fashion & Apparel Brands',
      'Product Photographers',
      'Advertising Agencies',
      'Catalogue Publishers',
      'Jewelry Retailers'
    ],
    customFaqs: [
      { q: "What is the delivery time for Clipping Path?", a: "Standard delivery is 24-48 hours. Rush options: 24hrs (+20%), 12hrs (+40%), 6hrs (+60%)." },
      { q: "Can I get a free trial?", a: "Yes! Submit up to 10 images free — no credit card required. Results in 24 hours." },
      { q: "What is your pricing model?", a: "Pricing starts from $0.25/image. Basic ($0.25), Medium ($0.49), Complex ($1.00), Super Complex ($3.00+). Volume discounts on orders of 1000+ images." },
      { q: "Do you sign NDAs?", a: "Yes. We sign NDAs on request. Your files are never shared without written permission." },
      { q: "How are files delivered?", a: "Via FTP, Dropbox, WeTransfer or Google Drive in PNG, PSD, TIFF or JPG format." }
    ],
    h2Title: 'What is Clipping Path Service?',
    beforeImage: '/bg-removal.jpg',
    afterImage: '/bg-removal-done.jpg',
    heroImage: '/bg-removal-done.jpg',
    order: 3,
    status: 'PUBLISHED'
  },
  {
    id: 's4',
    title: 'Ghost Mannequin',
    slug: 'ghost-mannequin-service',
    shortDescription: 'Create high-end 3D apparel visuals by removing mannequins and joining neck parts.',
    description: '<p>Give your apparel a professional 3D look. We expertly combine multiple shots to remove mannequins, leaving only the garment in a perfectly shaped "ghost" form.</p>',
    priceStarting: 0.75,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Seamless neck joints', 'Inner tag preservation', 'Symmetrical shaping', 'Texture detail enhancement'],
    beforeImage: '/Ghost-Mannequin-2-Raw.jpg',
    afterImage: '/Ghost-Mannequin-2-Done.jpg',
    order: 4,
    status: 'PUBLISHED'
  },
  {
    id: 's5',
    title: 'Image Masking',
    slug: 'image-masking-service',
    shortDescription: 'Complex masking for hair, fur, and transparent objects.',
    description: '<p>When clipping paths fall short, image masking takes over. We use advanced alpha channel and layer masking to preserve every strand of hair or fur against any background.</p>',
    priceStarting: 0.75,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Alpha channel masking', 'Hair & fur preservation', 'Translucency handling', 'Precision edge refining'],
    beforeImage: '/Masking-Retouch-Service-3.jpg',
    afterImage: '/Masking-Retouch-Service-Done-3.jpg',
    order: 5,
    status: 'PUBLISHED'
  },
  {
    id: 's6',
    title: 'Shadow & Reflection',
    slug: 'shadow-reflection-service',
    shortDescription: 'Realistic lighting effects to ground your products and add dimension.',
    description: '<p>Don\'t let your products float. We add natural drop shadows, reflection shadows, or original shadow preservation to create depth and professional realism.</p>',
    priceStarting: 0.45,
    priceUnit: 'image',
    turnaround: '12-24 hours',
    features: ['Natural drop shadows', 'Mirror reflections', 'Original shadow retention', 'Custom lighting angles'],
    beforeImage: '/Reflection-Service.jpg',
    afterImage: '/Reflection-Service-Done.jpg',
    order: 6,
    status: 'PUBLISHED'
  },
  {
    id: 's7',
    title: 'Beauty & Skin Retouch',
    slug: 'beauty-skin-retouching-service',
    shortDescription: 'High-end frequency separation and editorial skin retouching.',
    description: '<p>Preserve natural skin texture while eliminating blemishes. We use advanced editorial techniques for high-fashion results that look natural, not plastic.</p>',
    priceStarting: 2.00,
    priceUnit: 'image',
    turnaround: '24-48 hours',
    features: ['Frequency Separation', 'Advanced Dodge & Burn', 'Digital Makeup', 'Texture preservation'],
    beforeImage: '/Beauty-Retouch-Service-Page.jpg',
    afterImage: '/Beauty-Retouch-Service-Page-Done.jpg',
    order: 7,
    status: 'PUBLISHED'
  },
  {
    id: 's8',
    title: 'Model Retouch',
    slug: 'model-retouching-service',
    shortDescription: 'Full-body fashion and editorial model enhancements.',
    description: '<p>Complete model post-production. From clothing wrinkle removal to body reshaping and overall color grading for editorial and fashion catalogs.</p>',
    priceStarting: 1.99,
    priceUnit: 'image',
    turnaround: '24-48 hours',
    features: ['Body contouring', 'Wrinkle removal', 'Eye & teeth brightening', 'Tone normalization'],
    beforeImage: '/Model-Retouch-1.jpg',
    afterImage: '/Model-Retouch-1-Done.jpg',
    order: 8,
    status: 'PUBLISHED'
  },
  {
    id: 's9',
    title: 'Product Retouch',
    slug: 'product-retouching-service',
    shortDescription: 'Commercial-grade clean-up for durable goods, tools, and electronics.',
    description: '<p>Make your physical products look perfect. We remove surface imperfections, fingerprints, and dust while optimizing colors and contrast for sharp commercial appeal.</p>',
    priceStarting: 0.99,
    priceUnit: 'image',
    turnaround: '12-24 hours',
    features: ['Dust & scratch removal', 'Color matching', 'Perspective correction', 'Label enhancement'],
    beforeImage: '/Product-Retouch-Service-Page.jpg',
    afterImage: '/Product-Retouch-Service-Page-Done.jpg',
    order: 9,
    status: 'PUBLISHED'
  },
  {
    id: 's10',
    title: 'Jewelry Retouch',
    slug: 'jewelry-retouching-service',
    shortDescription: 'High-clarity precision retouching for diamonds, gems, and metals.',
    description: '<p>Jewelry requires extreme attention to detail. We enhance the brilliance of gemstones and the luster of metals while removing microscopic imperfections.</p>',
    priceStarting: 2.00,
    priceUnit: 'image',
    turnaround: '24-48 hours',
    features: ['Stone brightening', 'Metal polishing', 'Reflection management', 'Focus stacking'],
    beforeImage: '/Jewlery-Retouch-5.jpg',
    afterImage: '/Jewlery-Retouch-5-Done.jpg',
    order: 10,
    status: 'PUBLISHED'
  },
  {
    id: 's11',
    title: 'Color Correction',
    slug: 'color-correction-service',
    shortDescription: 'Vibrant and accurate color matching for your products.',
    description: '<p>Ensuring true-to-life colors is critical. We adjust white balance, exposure, and saturation to match your physical products exactly for accurate representation.</p>',
    priceStarting: 0.50,
    priceUnit: 'image',
    turnaround: '12 hours',
    features: ['White balance adjustment', 'Exposure correction', 'Selective color grading', 'Contrast optimization'],
    beforeImage: '/Color-Change.jpg',
    afterImage: '/Color-Change-Done.jpg',
    order: 11,
    status: 'PUBLISHED'
  },
  {
    id: 's12',
    title: 'Image Manipulation',
    slug: 'image-manipulation-service',
    shortDescription: 'Complex compositing and creative image transformations.',
    description: '<p>Transform your images into creative works of art. We expertly combine multiple elements, swap backgrounds, and manipulate reality for marketing and conceptual needs.</p>',
    priceStarting: 5.00,
    priceUnit: 'image',
    turnaround: '48-72 hours',
    features: ['Compositing', 'Creative background swapping', 'Object removal/addition', 'Conceptual art'],
    beforeImage: '/Image-Manipulation.jpg',
    afterImage: '/Image-Manipulation-Done.jpg',
    order: 12,
    status: 'PUBLISHED'
  },
  {
    id: 's13',
    title: 'Flatlay Retouch',
    slug: 'flatlay-photo-editing-service',
    shortDescription: 'Overhead product arrangement retouching for clean, symmetrical layouts.',
    description: '<p>Optimize your top-down product shots. We align elements, remove wrinkles, and consolidate lighting for a perfectly balanced flatlay aesthetic.</p>',
    priceStarting: 1.50,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Symmetry correction', 'Wrinkle removal', 'Consistent lighting', 'Grid alignment'],
    beforeImage: '/Flatlay-1.jpg',
    afterImage: '/Flatlay-1-Done.jpg',
    order: 13,
    status: 'PUBLISHED'
  },
  {
    id: 's14',
    title: 'Multi Clipping Path',
    slug: 'multi-clipping-path-service',
    shortDescription: 'Modular paths for complex objects with multiple components or colors.',
    description: '<p>When you need to edit individual parts of an image. Multiple paths allow for color changes to specific sections without affecting the rest of the product.</p>',
    priceStarting: 1.50,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Isolated section control', 'Color-change ready', 'Multi-layer organization', 'Complex component mapping'],
    beforeImage: '/bg-removal.jpg',
    afterImage: '/bg-removal-done.jpg',
    order: 14,
    status: 'PUBLISHED'
  },
  {
    id: 's15',
    title: 'Real Estate Photo Editing',
    slug: 'real-estate-photo-editing',
    shortDescription: 'High-impact property enhancements for realtors and developers.',
    description: '<p>Sell properties faster with stunning visuals. We handle HDR blending, sky replacement, grass greening, and vertical alignment for perfect architectural shots.</p>',
    priceStarting: 2.00,
    priceUnit: 'image',
    turnaround: '24 hours',
    features: ['Sky replacement', 'HDR blending', 'Lens correction', 'Vertical/horizontal leveling'],
    beforeImage: '/Real-Estate-Before.png',
    afterImage: '/Real-Estate-After.png',
    order: 15,
    status: 'PUBLISHED'
  },
  {
    id: 's16',
    title: 'Car Photo Editing',
    slug: 'car-photo-editing-service',
    shortDescription: 'Professional automotive retouching and showroom-ready finishes.',
    description: '<p>High-end retouching for car dealerships and collectors. We remove reflections, enhance metallic finishes, and place vehicles in clean digital showrooms.</p>',
    priceStarting: 3.00,
    priceUnit: 'image',
    turnaround: '24-48 hours',
    features: ['Reflection clean-up', 'Paint brightness boost', 'Tire/rim polishing', 'Showroom background swap'],
    beforeImage: '/Car-Before.jpg',
    afterImage: '/Car-After.jpg',
    order: 16,
    status: 'PUBLISHED'
  },
  {
    id: 's17',
    title: '360° Product Editing',
    slug: '360-degree-product-photo-editing',
    shortDescription: 'Precise batch editing for interactive 360-degree spinners.',
    description: '<p>Interactive products require extreme consistency across frames. we batch process your 360-degree sequences to ensure perfect alignment and color across every rotation degree.</p>',
    priceStarting: 0.75,
    priceUnit: 'frame',
    turnaround: '48 hours',
    features: ['Batch consistency', 'Rotational alignment', 'Consistent exposure', 'Automated workflow support'],
    beforeImage: '/ECommerce.jpg',
    afterImage: '/ECommerce-Done.jpg',
    order: 17,
    status: 'PUBLISHED'
  },
  {
    id: 's18',
    title: 'Packshot Retouching',
    slug: 'packshot-retouching-service',
    shortDescription: 'Clean, standard product shots for retail and inventories.',
    description: '<p>Standardizing packshot images for e-commerce. Clean backgrounds, standard margins, and color-accurate representation for retail platforms.</p>',
    priceStarting: 0.99,
    priceUnit: 'image',
    turnaround: '12-24 hours',
    features: ['Shadow creation', 'Standardized centering', 'Label straightening', 'Batch processing'],
    beforeImage: '/ECommerce.jpg',
    afterImage: '/ECommerce-Done.jpg',
    order: 18,
    status: 'PUBLISHED'
  },
  {
    id: 's19',
    title: 'Image Web Optimization',
    slug: 'image-web-optimization-service',
    shortDescription: 'High-performance compression and formatting for the web.',
    description: '<p>Don\'t compromise speed for quality. We optimize your images with precision compression, WebP conversion, and responsive sizing to boost your site\'s SEO and performance.</p>',
    priceStarting: 0.25,
    priceUnit: 'image',
    turnaround: '6-12 hours',
    features: ['Lossless compression', 'WebP/Avif formatting', 'SEO metadata syncing', 'Responsive size generation'],
    beforeImage: '/bg-removal.jpg',
    afterImage: '/bg-removal-done.jpg',
    order: 19,
    status: 'PUBLISHED'
  },
  {
    id: 's20',
    title: 'Photo Restoration',
    slug: 'photo-restoration-service',
    shortDescription: 'Bringing damaged, old, or faded photographs back to life.',
    description: '<p>Restore your precious memories. We repair cracks, remove stains, colorize monochrome shots, and rebuild missing parts of legacy photographs.</p>',
    priceStarting: 7.00,
    priceUnit: 'image',
    turnaround: '48-72 hours',
    features: ['Scratch/tear repair', 'Stain removal', 'Colorization', 'Detail reconstruction'],
    beforeImage: '/Photo-Restoration-Before.png',
    afterImage: '/Photo-Restoration-After.png',
    order: 20,
    status: 'PUBLISHED'
  }
];

export const portfolio = [
  { id: 'p1', title: 'Retail E-Commerce Batch', category: 'ecommerce-photo-editing', serviceName: 'E-Commerce', beforeImage: '/ECommerce.jpg', afterImage: '/ECommerce-Done.jpg', featured: true },
  { id: 'p2', title: 'Luxury Furniture Cut-out', category: 'background-removal-service', serviceName: 'Background Removal', beforeImage: '/bg_removal_compare_before_1774788191480.png', afterImage: '/bg_removal_compare_after_1774788208396.png', featured: true },
  { id: 'p3', title: 'Vector Pen Tool Clipping', category: 'clipping-path-service', serviceName: 'Clipping Path', beforeImage: '/bg-removal.jpg', afterImage: '/bg-removal-done.jpg', featured: true },
  { id: 'p4', title: '3D Ghost Mannequin Denim', category: 'ghost-mannequin-service', serviceName: 'Ghost Mannequin', beforeImage: '/Ghost-Mannequin-2-Raw.jpg', afterImage: '/Ghost-Mannequin-2-Done.jpg', featured: true },
  { id: 'p5', title: 'Fine Hair Masking', category: 'image-masking-service', serviceName: 'Image Masking', beforeImage: '/Masking-Retouch-Service-3.jpg', afterImage: '/Masking-Retouch-Service-Done-3.jpg', featured: true },
  { id: 'p6', title: 'Reflection Shadow Finish', category: 'shadow-reflection-service', serviceName: 'Shadow & Reflection', beforeImage: '/Reflection-Service.jpg', afterImage: '/Reflection-Service-Done.jpg', featured: true },
  { id: 'p7', title: 'High-End Editorial Skin', category: 'beauty-skin-retouching-service', serviceName: 'Beauty Retouch', beforeImage: '/Beauty-Retouch-Service-Page.jpg', afterImage: '/Beauty-Retouch-Service-Page-Done.jpg', featured: true },
  { id: 'p8', title: 'Fashion Model Shoot', category: 'model-retouching-service', serviceName: 'Model Retouch', beforeImage: '/Model-Retouch-1.jpg', afterImage: '/Model-Retouch-1-Done.jpg', featured: true },
  { id: 'p9', title: 'Electronic Item Clean', category: 'product-retouching-service', serviceName: 'Product Retouch', beforeImage: '/Product-Retouch-Service-Page.jpg', afterImage: '/Product-Retouch-Service-Page-Done.jpg', featured: true },
  { id: 'p10', title: 'Jewelry Diamond Luster', category: 'jewelry-retouching-service', serviceName: 'Jewelry Retouch', beforeImage: '/Jewlery-Retouch-5.jpg', afterImage: '/Jewlery-Retouch-5-Done.jpg', featured: true },
  { id: 'p11', title: 'Product Color Correction', category: 'color-correction-service', serviceName: 'Color Correction', beforeImage: '/Color-Change.jpg', afterImage: '/Color-Change-Done.jpg', featured: true },
  { id: 'p12', title: 'Creative Background Swap', category: 'image-manipulation-service', serviceName: 'Image Manipulation', beforeImage: '/Image-Manipulation.jpg', afterImage: '/Image-Manipulation-Done.jpg', featured: true },
  { id: 'p13', title: 'Tabletop Flatlay Alignment', category: 'flatlay-photo-editing-service', serviceName: 'Flatlay Retouch', beforeImage: '/Flatlay-1.jpg', afterImage: '/Flatlay-1-Done.jpg', featured: true },
  { id: 'p15', title: 'Architecture HDR Blend', category: 'real-estate-photo-editing', serviceName: 'Real Estate', beforeImage: '/Real-Estate-Before.png', afterImage: '/Real-Estate-After.png', featured: true },
  { id: 'p20', title: 'Old Photograph Recovery', category: 'photo-restoration-service', serviceName: 'Photo Restoration', beforeImage: '/Photo-Restoration-Before.png', afterImage: '/Photo-Restoration-After.png', featured: true }
];

export const faqs = [
  { id: 'f1', question: 'What is your standard turnaround time?', answer: 'Most orders are delivered within 24 hours. Express options (12 hours) are available for urgent projects.', category: 'general' },
  { id: 'f2', question: 'Do you offer a free trial?', answer: 'Yes! You can upload up to 3 images for a free trial to evaluate our quality before placing a bulk order.', category: 'pricing' },
  { id: 'f3', question: 'What file formats do you accept?', answer: 'We accept all major formats including JPG, PNG, PSD, TIFF, and RAW files from all camera manufacturers.', category: 'technical' },
  { id: 'f4', question: 'Is my data secure with Blackfox?', answer: 'Absolutely. We maintain strict NDAs and use secure, encrypted servers for all file transfers. Your images are never shared with third parties.', category: 'security' }
];

export const testimonials = [
  { id: 't1', clientName: 'Sarah Jenkins', company: 'Luxe Fashion House', message: 'The quality of their ghost mannequin work is unparalleled. They saved our e-commerce catalog launch.', rating: 5, avatar: null },
  { id: 't2', clientName: 'Marco Rossi', company: 'Global Photo Agency', message: 'Reliable, fast, and surgical precision. Blackfox is our go-to partner for all volume retouching.', rating: 5, avatar: null }
];

export const teamMembers = [
  { id: 'tm1', name: 'Zahirul Islam', role: 'Head of Production', bio: '12+ years of experience in high-end retouching workflows.', avatar: null },
  { id: 'tm2', name: 'Emma Watson', role: 'Quality Control Lead', bio: 'Expert in pixel-perfect accuracy and brand guideline adherence.', avatar: null }
];

export const siteSettings = {
  siteName: "Blackfox Digital",
  copyright: "© 2026 BLACKFOX DIGITAL. All Rights Reserved.",
  logoUrl: "/logo.png",
  phone1: "(+88) 019 24 482 868",
  phone2: "(+88) 018 41 482 868",
  email: "info@theblackfoxstudio.com",
  addressHQ: "House 560, Road 08, Adabor, Dhaka 1207",

  facebookUrl: "https://www.facebook.com/theblackfoxstudio/",
  instagramUrl: "https://www.instagram.com/",
  linkedinUrl: "https://bd.linkedin.com/company/the-black-fox-studio",
  whatsappUrl: "https://wa.me/01924482868",
  youtubeUrl: "https://www.youtube.com/",
  teamsUrl: "https://teams.microsoft.com/"
};
